### ISSUE TITLE
TZX enhancement

### ISSUE THREAD

**Issue by rossimariolee** [raydac/zxpoly#10]
Could you add the TZX file format load system ?

**Comment by raydac** [comment]
the idea is interesting one but I am not sure that will be able to implement support during this release or next one, because [TZX is a format which was developed for complex support of records even with protection](http://k1.spdns.de/Develop/Projects/zasm/Info/TZX%20format.html) and can keep not only data but even sound and it is very big piece of work to support it

**Comment by PakkunKinoppi** [comment]
Hi, I would be a great thing.
TZX archive has got a lot of software about our beloved ZXs.

This is a great emulator Java and OSX arm ...Great!
I'll follow you!

...don't miss the Cursor Joystick implementation I'll be very usefull in some software ! (Can I open an issue about ?)

Thank you

**Comment by raydac** [comment]
not very understand what do you mean as cursor joystick

**Comment by PakkunKinoppi** [comment]
Cursor Joystick Interface was my Joystick cartridge:

In some games and software I used select (Cursor Joystick)
I owned a ZX1 and ZX2 interface not kempston:
https://en.wikipedia.org/wiki/ZX_Interface_2

**Comment by Alessandro1970** [comment]
Cursor Joystick was a cartridge used to connect joystick in England, Italy and France as I remembre in 1985 ...when I was quite young ... :sob: 
Cursor joystick interfaces maps to keys 5 (left), 6 (down), 7 (up), 8 (right) and 0 (fire). Reading a cursor joystick thus requires a combination of bit 4 of port 0xf7fe and bits 0, 2, 3 and 4 of port 0xeffe. Common interfaces offering a cursor joystick option included those produced by Protek and AGF.
![download](https://user-images.githubusercontent.com/34916641/108362378-f1a44b80-71f3-11eb-8c80-a76fbd059b64.jpg)

**Comment by PakkunKinoppi** [comment]
@Alessandro1970 You are right.
Too many years... 
It was a Protek and used the cursor keys in games and software. The colour was different but you are right, thanks.

**Comment by Alessandro1970** [comment]
...Fairlight !!!  :tada: 

![hqdefault](https://user-images.githubusercontent.com/34916641/108364079-eeaa5a80-71f5-11eb-8a73-c630560ead6e.jpg)

**Comment by PakkunKinoppi** [comment]
no, no ..another mistake, memory fade down!

not that, FIRELORD it was:
![f48ec15d8e88862411847c86578eba1f](https://user-images.githubusercontent.com/52820759/108364294-30d39c00-71f6-11eb-80e0-27e120bdaaac.png)

**Comment by raydac** [comment]
if you mean mapping of PC cursor keys then it is already presented and you can play "cursor joystick" with cursor keys on your keyboard

**Comment by rossimariolee** [comment]
There were a lot of similar cartridge.

I think that @PakkunKinoppi  was asking for this implementation:

![Untitled 2](https://user-images.githubusercontent.com/41687618/108367582-e3f1c480-71f9-11eb-9dc3-a29b50070645.png)

**Comment by raydac** [comment]
I not very understand how such peripheral should look from implementation side, now it maps by default cursor keys to zx cursor keys and if any external game controller then it is separate part and it doesn't play role cursor or kempston

**Comment by PakkunKinoppi** [comment]
Ok, I have seen it,  " doesn't play role cursor or kempston", you are right.
I in other emulator I used it in different ways buy your one is very good as it is.
Thanks

**Comment by raydac** [comment]
I have tried to convert a TZX file with complex loader (with protection) into a WAV file and load as Tape sound file (as converter utility tape2wav from fuse-utils), looks working

**Comment by Alvarez81** [comment]
Hi, are there some news for loading TZX games on ZxPoly ?

**Comment by PakkunKinoppi** [comment]
Hallo, at this point a **tzx loader enhancement** would be fine.
A lot of software for spectrum can be found on TZX vault site, and ZxPoly is a great emulator for Apple Silicon too (it works well in M1 native mode, never hangs till now).

**Comment by rossimariolee** [comment]
TZX is the best tape format for preservation. So one can find the best software in the best way of preservation.
I hope that ZxPoly will support it as soon as possible because this is a great emulator that could become a cult for its portability and good compatibility. Thank you for the virtual keyboards selection mode, they are all beautiful and user friendly.

**Comment by Alvarez81** [comment]
@raydac 
I converted a Tzx game to wav it worked but it was too large file, 20Mb for one game.
I cannot convert all games to wav, pobably a tzx support would be better for this great emulator.

**Comment by raydac** [comment]
I have added initial support of TZX tape snapshots into SNAPSHOT version, I have found only TZX files with standard and turbo blocks if anyone has TZX files with some complex protection then it would be good to provide them for testing

**Comment by Alvarez81** [comment]
The tzx loader system seems to work fine, but is there any way to load game a bit faster ? ...like fuse, few seconds
