### ISSUE TITLE
Cannot use kempston in game

### ISSUE THREAD

**Issue by PakkunKinoppi** [raydac/zxpoly#11]
I select kempston joystick from game menu but the character does not move, kempston does not work

[Nosferatu The Vampyre (1986)(Macmillan).zip](https://github.com/raydac/zxpoly/files/6008679/Nosferatu.The.Vampyre.1986.Macmillan.zip)

...here too>
[Samurai Warrior - Usagi Yojimbo (1988)(Firebird).zip](https://github.com/raydac/zxpoly/files/6008698/Samurai.Warrior.-.Usagi.Yojimbo.1988.Firebird.zip)

**Comment by raydac** [comment]
which OS, which gamepad, if you make screenshot with game controllers menu it also will be good

**Comment by PakkunKinoppi** [comment]
I-m using Windows 8, no gamepad only keyboard.
But the emulation of kempston as image below works in Slap Fight Game but in theese two no

![Untitled 4](https://user-images.githubusercontent.com/52820759/108482768-34b8fa00-729a-11eb-82ce-bdeaa3544fb5.png)

**Comment by PakkunKinoppi** [comment]
[Castle Master (1990)(Incentive).zip](https://github.com/raydac/zxpoly/files/6008817/Castle.Master.1990.Incentive.zip)
Here the same, if I select kempstone the keys selected do non work.

If I select keyboard in the game menu it works, there are some problems in kempstone assignment or someting related

**Comment by PakkunKinoppi** [comment]
This (slaptfight) works well with kempston and the same configuration.

It seems to me that some games do not work with this kempston emulation

[Slap Fight (1987)(Imagine Software)(128k).zip](https://github.com/raydac/zxpoly/files/6008851/Slap.Fight.1987.Imagine.Software.128k.zip)

**Comment by Alessandro1970** [comment]
Hi, for me too SamuraWarrior does't work with kempstone emulation in Zxpoly, on fuse it works with the same keys assigned for kempston.

**Comment by Alessandro1970** [comment]
I used Terramex game with this configuration and selecting kempston the "hand" doesn't move in the right way (some keys are wrong).
[Terramex (1987)(Argus Press Software)(128k).zip](https://github.com/raydac/zxpoly/files/6008924/Terramex.1987.Argus.Press.Software.128k.zip)

![Untitled 6](https://user-images.githubusercontent.com/34916641/108486295-3a184380-729e-11eb-9833-ab3b428883bb.jpg)

**Comment by raydac** [comment]
looks like that it is the same problem - program get notification from keyboard and kempston in same time because shared keys in use, I think to add some selectable mode in options meny when only kempston events will be send

**Comment by raydac** [comment]
looks like that it is the same problem - program get notification from keyboard and kempston in same time because shared keys in use, I think to add some selectable mode in options menu when only kempston events will be sent

**Comment by raydac** [comment]
I have added filtering for only Kempston events if such mode is turned on (F6 or flag in Options menu list), ZX-Keyboard in such mode accessible only with pressed CTRL, you can try snapshot

**Comment by Alessandro1970** [comment]
Sorry, I’m trying now the snapshot with F6 but the character in Nosferatu game does not move.
It seems to me that the game does not recognize kempston

**Comment by Alessandro1970** [comment]
![8450FC43-AC29-4990-A530-27195E41B921](https://user-images.githubusercontent.com/34916641/108588592-54175c00-735a-11eb-9462-4681cad38bac.jpeg)
This is my config with new snapshot
This the game whit kempston selected
![93055265-140D-41C6-AAA5-14C027528CE9](https://user-images.githubusercontent.com/34916641/108588656-a2c4f600-735a-11eb-8711-3919982d0fed.jpeg)

**Comment by raydac** [comment]
I have tried Nosferatu even with NUMPAD keys, looks like the game has very specific kempston processing because under FUSE emulator the game also not playable with kempston

**Comment by raydac** [comment]
I decoding Kempston port as UnrealSpeccy through low port address byte mask 00100000

**Comment by Alessandro1970** [comment]
In fuse the game works with protek interface with my arrows key
![203B52BB-2479-4D9B-B7FF-192CDEF021DD](https://user-images.githubusercontent.com/34916641/108589853-c25f1d00-7360-11eb-9793-5fd82e515e96.jpeg)

**Comment by Alessandro1970** [comment]
The problem is that if I would like to select keys from game and I use my arrows key the emulator does not recognize them:
Look here all my arrows key are seen as capsh shift
![9CF7CB8F-9869-4E67-AB36-CDFC575D9D3F](https://user-images.githubusercontent.com/34916641/108590112-16b6cc80-7362-11eb-96ba-65f6adba55d6.jpeg)

**Comment by Alessandro1970** [comment]
![Uploading 8F87B002-83E1-4D7E-8AED-EEA21D3AE8A3.jpeg…]()

**Comment by Alessandro1970** [comment]
![68E312A1-DC59-4ECF-85BD-3C71A6CC7B63](https://user-images.githubusercontent.com/34916641/108590233-9a70b900-7362-11eb-9313-2f69d9008c2c.jpeg)

**Comment by raydac** [comment]
cursor keys mapped to CS+6,7,8,9 and as I see the game recognizing only first bit in keyboard state, looks like that the game, I can add flag in preferences to disable map cursor keys on CS+.. and in the case it will be working

**Comment by raydac** [comment]
made snapshot with option to unmap cursor keys from CS but looks like that it will not help in case of the game, the game developed in such bizarre style that even key redefinition works only for half of keyboard, I have tried under FUSE and see same picture

**Comment by raydac** [comment]
@Alessandro1970 
try define such keys for Nosferatu, it looks very strange but with such keys the game can be played by PC cursor keys on my machine
![image](https://user-images.githubusercontent.com/3008810/108594030-2fce7600-7380-11eb-9167-33501e738295.png)

**Comment by Alessandro1970** [comment]
Ok,
there are a lot of problems in those games and assign the keys on pc or mac.

On the pc I succeed in assigning the arrows key to move, on the mac no (there are no corrispondecies).
BTW Zynaps or Uridium work well with ZxPoly and emulated kempston.
I think that it could be useful assign the mapping Kempston keys not using a list but input keypressing directly (for the right corrispondency Layout or different system)

**Comment by Alessandro1970** [comment]
![Untitled 2](https://user-images.githubusercontent.com/34916641/108703100-751eaf00-750a-11eb-941c-77f23bc81bd5.png)
I mean something like this, selection by pressing keys on keyboard not from a list

**Comment by Alessandro1970** [comment]
![ttt](https://user-images.githubusercontent.com/34916641/108703298-b911b400-750a-11eb-83de-1b1659d04d9c.jpg)

I mean something like this, the selection pressing keys on the keyboard and not from a prebuilt list.

**Comment by Alessandro1970** [comment]
I mean something like this, the selection pressing keys on the keyboard and not from a prebuilt list:
![ttt](https://user-images.githubusercontent.com/34916641/108703446-ebbbac80-750a-11eb-8269-80e34ac4cb57.jpg)

**Comment by raydac** [comment]
good idea, now I have provide just a list of all Java keys for speed but will try to make some custom component providing select through pressing

**Comment by raydac** [comment]
@Alessandro1970 I have improved key chooser, you can try snapshot

**Comment by Alessandro1970** [comment]
@raydac Ok, in this way it works for me.

For Nosferatu or similar games I think that the only solution is to implement a Protek/AGF, so users can select/redefine theirs keys mapped to pc/mac/linux keyboard like kempston interface; where kempston cannot maybe other joystick kind selectable.

**Comment by PakkunKinoppi** [comment]
@raydac 

Now is better, but the only soluction could be to implement the Interface2 and Protek joystick in the same way of the kempston.
So we could select something other kempston when the game doesn't accept it.

**Comment by raydac** [comment]
I have added support for Cursor joystick in SNAPSHOT version, it can be configurable in Preferences and should be selected instead of Kempston through `Options->Joystick->Cursor`

**Comment by PakkunKinoppi** [comment]
Sorry, I cannot use the cursor joystick in this game:
[Druid (1986)(Firebird)[a].zip](https://github.com/raydac/zxpoly/files/6034009/Druid.1986.Firebird.a.zip)

**Comment by raydac** [comment]
@PakkunKinoppi looks like that the snapshot is not-correct, I have tried SCL disk version of Druid from [Virtual TRDOS](https://vtrd.in/gamez/d/DRUID_1.ZIP) and it works well with cursor joystick, under FUSE your snapshot works similarly my emulator

**Comment by Alessandro1970** [comment]
@raydac  @PakkunKinoppi 
Hi,
there are a lot off snapshott fully buggy on the net.
Here there are these 3 really ok:
[Druid.tap.zip](https://github.com/raydac/zxpoly/files/6034627/Druid.tap.zip)
[DruidII-Enlightenment.tap.zip](https://github.com/raydac/zxpoly/files/6034628/DruidII-Enlightenment.tap.zip)
[Nosferatu.zip](https://github.com/raydac/zxpoly/files/6034629/Nosferatu.zip)

Now ZxPoly works well with kempston and cursor interface. Nosferatu is kempston fully working.
Thanks
bye

**Comment by PakkunKinoppi** [comment]
All in ZXPOLY is working fine for me too.

Thank you
