### ISSUE TITLE
Virtual keyboard and sticky keys (caps shift must be released after the first click)

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#12]
Hi,
If I press the "symbol shift" than the "caps shift" after pressind this last it must be deselected beacuse the letter will turn quickly from K mode to E mode.
All the two caps must not remain selected (capsshift must be released after the first click).
![Untitled 8](https://user-images.githubusercontent.com/34916641/108492559-992d8680-72a5-11eb-9a82-60b06bbeed0f.jpg)

**Comment by raydac** [comment]
fix caps shift only until first non caps shift key pressed?

**Comment by Alessandro1970** [comment]
If you press symbolshift + capsshift the mode will turn from K to E but the keys must be released in the virtual keyboard, otherwise they remains pressed.
In other way if you have to change mode press the Symboshift (sticky) and when you will press the capsshift the input will turn the mode from K to E on the screen but the two keys have to be released (the green circle must turn away) after pressing the second key (caps shift).

**Comment by Alessandro1970** [comment]
Video:
[Img 4059-1.zip](https://github.com/raydac/zxpoly/files/6009831/Img.4059-1.zip)

Fixing capshif means that capshift when pressed will release also the symbolshift (in that moment sticky)

**Comment by raydac** [comment]
there is some problem that it is asynchronous  system and the logic is situated inside emulated ZX-Spectrum SOS, so that we can't be sure that auto-release will be processed correctly in time because it can be too early or too late

**Comment by Alessandro1970** [comment]
...or release after click if there is still another key pressed

**Comment by raydac** [comment]
will try to attach the action to INT ticks

**Comment by raydac** [comment]
you can try snapshot

**Comment by Alessandro1970** [comment]
Great!
It works fine.
Thank you
