### ISSUE TITLE
Load .taps games faster

### ISSUE THREAD

**Issue by Haroldo64** [raydac/zxpoly#13]
Hello everyone, the loading speed of the .tap files seems to me quite slow, I don't remember if it's like the original.
Could there be a way to load .taps games faster?
Greetings to all

**Comment by raydac** [comment]
you can press F3 during loading to turn on turbo mode and press F3 again after loading to turn it off, the emulator doesn't use any trap points to inject data and all tape loading work like as on real spectrum through TAPE port

**Comment by Haroldo64** [comment]
It's good, F3 works well
