### ISSUE TITLE
General Instrument AY-3-8910 on-off

### ISSUE THREAD

**Issue by Haroldo64** [raydac/zxpoly#14]
Is there any way to select the General Instrument AY-3-8910 sound chip in 128k mode ?

Bye

**Comment by raydac** [comment]
what do you mean?

**Comment by Haroldo64** [comment]
Is the 128k sound chip supported ?
I do not see any setting about

**Comment by raydac** [comment]
emulator has emulation of AY8910 and TurboSound (2xAY8910), TurboSound can be turned on through Preferences and AY8910 presented in port space everytime so that should be audible if you activate sound system in Options->Sound

**Comment by Haroldo64** [comment]
Ok, probably I have used some buggy games, no AY8910 heard in those moments.

**Comment by raydac** [comment]
if you don't hear sound then check Sound option in Options because for instance Turbo mode can turn it off
