### ISSUE TITLE
Filters and Interpolate Video

### ISSUE THREAD

**Issue by rossimariolee** [raydac/zxpoly#15]
Hello, could you add the color filters AMBER CRT/GREEN CRT and the interpolate video filters EPX and EAGLE ?

**Comment by raydac** [comment]
I am not sure in interpolation because in Java I use its internal hardcoded mechanisms for scaling, make any custom scaling can kill speed of work and Green/Orange CRT I guess not a problem

**Comment by Alessandro1970** [comment]
ZxPoly's Gaussian filter is good for many games

**Comment by Alessandro1970** [comment]
This is it on my pc:

![Untitled 3](https://user-images.githubusercontent.com/34916641/109122893-89042400-7749-11eb-9d99-2d8680ec3701.png)

**Comment by Haroldo64** [comment]
...what's the hell, No spectrum, that's Amiga !?

**Comment by Alessandro1970** [comment]
Not a Commodore Amiga nor ST, that is **ZxPoly** !!!

http://www.emulatronia.com/emusdaqui/spec256/download-eng.htm

**Comment by raydac** [comment]
it is a Spec256 game, with 256 colors under virtual 64 bit Z80, and ZX-Poly simulates 4 real Z80 and has only 16 coloers per pixel

**Comment by raydac** [comment]
@rossimariolee I have added Amber old TV and Green old TV filters, you can try snapshot

**Comment by rossimariolee** [comment]
thanks
