### ISSUE TITLE
ULA-Plus settings

### ISSUE THREAD

**Issue by rossimariolee** [raydac/zxpoly#16]
Is there the way tu turn on ULA-Plus ?
Thank you

**Comment by raydac** [comment]
there is no way, the emulator was developed to emulate ZX-Poly and in Spec128 I just filtering some calls to increase compatibility with ZX-Spectrum 128 so that it not simulates some specific things and work with abstract ZX128 platform

**Comment by rossimariolee** [comment]
ok
