### ISSUE TITLE
Virtual keyboard button

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#17]
Hi,
could you add a button for faster SHOW/HIDE the virtual keyboard like in this picture ?

![Untitled 2](https://user-images.githubusercontent.com/34916641/109119034-6c192200-7744-11eb-9a99-c0a1dd444c2c.png)

**Comment by raydac** [comment]
good idea

**Comment by raydac** [comment]
@Alessandro1970 you can try snapshot

**Comment by Alessandro1970** [comment]
Thank you
