### ISSUE TITLE
ZxPoly does not keep the original size when switching back from full screen.

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#18]
ZxPoly does not keep the original size when switching back from full screen:
It should scale down

![Untitled 3](https://user-images.githubusercontent.com/34916641/109158256-6be44b00-7773-11eb-95a2-13879e5221cf.png)

**Comment by raydac** [comment]
@Alessandro1970 I made some refactoring you can try snapshot

**Comment by Alessandro1970** [comment]
Great, thank you !
