### ISSUE TITLE
Spites flashing

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#19]
Hi,
the sprites (main character and others) are flashings, what's the problem ?

[Gryzor (1987)(Ocean)[128K].zip](https://github.com/raydac/zxpoly/files/6068239/Gryzor.1987.Ocean.128K.zip)
[Ghouls Ghosts (1989)(U.S. Gold)[128K].zip](https://github.com/raydac/zxpoly/files/6068240/Ghouls.Ghosts.1989.U.S.Gold.128K.zip)

![Untitled 1](https://user-images.githubusercontent.com/34916641/109642717-9fe4b500-7b53-11eb-93d4-caf519d139a6.png)

**Comment by raydac** [comment]
usually such effect for games which using very fast video page blicking to show graphic effects for sprites, in Java it is hard to get such speed of screen refresh thus we see some flashing, I still think how to improve gfx module

**Comment by PakkunKinoppi** [comment]
Hello, I have run this java emulator that has got a z80 core, it has not any problem with refresh video and Gryzor works well also the emulator is at an early stage (it seems to me that is more commodore than sinclair but it has a spectrum core, try gryzor on it using the last beta that has that kind of support)
Greetings

https://www.z64k.com/resources/version2/Z64K.jar

**Comment by Haroldo64** [comment]
Hi, any news ?

**Comment by raydac** [comment]
I have found some potential solution, but it needs some time for development and testing

**Comment by Alessandro1970** [comment]
Any news abiut this issue?
Is there any possibility to be fixed ?

**Comment by raydac** [comment]
since 2.2.1 version there is interlacing and  if "interlaced scan" option is turned on  then whole sprite is visible but as interlaced one, I am trying implement contended ram delay but still without big success
![gryzor](https://user-images.githubusercontent.com/3008810/132988702-0d3bb667-14c5-46c5-a59f-061171039951.png)

**Comment by Alessandro1970** [comment]
I  played this game with last beta and it seems to me that the game works well, no more flashing. 
G'n'G works well too.
