### ISSUE TITLE
Some games with trainer hang

### ISSUE THREAD

**Issue by rossimariolee** [raydac/zxpoly#20]
Hi, this game hangs after choosing trainer (any option), on fuse it works.

[Wacky Races (1992)(Hi-Tec Software)[128K].zip](https://github.com/raydac/zxpoly/files/6084061/Wacky.Races.1992.Hi-Tec.Software.128K.zip)

**Comment by raydac** [comment]
could you provide trainer file

**Comment by rossimariolee** [comment]
The trainer starts when you run the game, try on fuse

**Comment by raydac** [comment]
looks like that some incompatibility with the trainer block, original game loaded from TZX (converted into WAV) TAPE works well, disk SCL version from Virtual TR-DOS with cheat codes also works well, will see

**Comment by raydac** [comment]
could you try with 2.2.3-SNAPSHOT?

**Comment by rossimariolee** [comment]
Using last snapshot it works well, thank you
