### ISSUE TITLE
Gauntlet 3 hangs

### ISSUE THREAD

**Issue by Haroldo64** [raydac/zxpoly#21]
Hi, Gauntlet 3 hangs, cannot play.

[GAUNTL_3_trd.zip](https://github.com/raydac/zxpoly/files/6115797/GAUNTL_3_trd.zip)

![Untitled 1](https://user-images.githubusercontent.com/53178600/110629938-0e092780-81a5-11eb-850c-bb0c751a1562.png)

**Comment by raydac** [comment]
looks like that some incompatibility in beta-disk controller implementation, this tape to disk adaptation doesn't work but adaptation from Code Busters works well

**Comment by Alessandro1970** [comment]
...but doesn't work either the tap files 
[Gauntlet 3.zip](https://github.com/raydac/zxpoly/files/6116285/Gauntlet.3.zip)

But on Speccy emulator it works

**Comment by raydac** [comment]
I have improved emulation of FDD
