### ISSUE TITLE
Camelot Warriors hangs

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#22]
Hi, this game hangs while loading, it works on fuse.
[Camelot Warriors [48-128K].zip](https://github.com/raydac/zxpoly/files/6123618/Camelot.Warriors.48-128K.zip)

**Comment by raydac** [comment]
it doesn't hang, I don't know why but the TAP version non-correct in keyboard port procesing, may it was developed for some specific model of ZX-Spectrum. I have tried SCL version from VirtualTRDOS and TAP version from WoS, looks working and with the provided version it works like FIRE key is pressed permanently

**Comment by Alessandro1970** [comment]
Emulation problem at Joystick/keyboard selection

There is a version that bypass the joystick/keyboard selection and it works, strange !
[Camelot Warriors [K].zip](https://github.com/raydac/zxpoly/files/6139910/Camelot.Warriors.K.zip)

**Comment by Haroldo64** [comment]
The problem is not the game. 
ZxPoly han not got all z80 version "format loader",
Probably some version format are missing,

https://worldofspectrum.org/faq/reference/z80format.htm#:~:text=z80%20files%20are%20memory%20snapshots,but%20do%20load%20almost%20instantaneously.&text=z80%20format%20have%20also%20been%20made%20by%20other%20emulators.

**Comment by PakkunKinoppi** [comment]
...loading version 2, mode 4 Z80 snapshots ?

**Comment by raydac** [comment]
@Haroldo64 
the issue about incompatibility with some TAP loaded game, not Z80 snapshot

**Comment by PakkunKinoppi** [comment]
Version 2 and 3 .z80 files start with the same 30 byte header as version 1 files. However, bit 4 and 5 of the flag byte have no meaning anymore, and the program counter (byte 6 and 7) is zero to signal a version 2 or 3 file.
Camelot Warriors hangs beocause an incompatibility with ".z80" loader, try that game on Z64k java emulator (zx spectrum mode) it works

**Comment by PakkunKinoppi** [comment]
[Camelot Warriors (1986)(Ariolasoft UK).zip](https://github.com/raydac/zxpoly/files/6303299/Camelot.Warriors.1986.Ariolasoft.UK.zip)

This is the .z80 non working with ZxPoly

**Comment by raydac** [comment]
@PakkunKinoppi I was trying to start the snapshot under Fuse, differently but also doesn't work

**Comment by PakkunKinoppi** [comment]
Try it on java z64k:
https://www.z64k.com/

**Comment by Haroldo64** [comment]
May these Z80 core files be useful ?

[zilogz80.zip](https://github.com/raydac/zxpoly/files/6500947/zilogz80.zip)

**Comment by Alessandro1970** [comment]
Bug due to different ULA or other bug,
Download the fixed release of Camelot Warrior: 
#40 
For me works with last ZxPoly and the fixed version.
