### ISSUE TITLE
Doomdark Revenge hangs after loading

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#23]
Doomdark Revenge hangs after loading.
[Doomdark Revenge [48K].zip](https://github.com/raydac/zxpoly/files/6129010/Doomdark.Revenge.48K.zip)

**Comment by raydac** [comment]
describe step by step, I have tried load the TAP in `ZX-Mode` under 48 Basic and it starts

**Comment by Alessandro1970** [comment]
Ok, loaded from menu in Spectrum 48 mode
