### ISSUE TITLE
Darkside game reset during loading

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#24]
Darkside game reset during loading, but starts on fuse.
Maybe there are some loading .tap bugs.

[Darkside [48K].zip](https://github.com/raydac/zxpoly/files/6129092/Darkside.48K.zip)

**Comment by raydac** [comment]
I managed load and start the game without problems from the TAP.
1. ensure that `Options->ZX-Mode` is ON
2. load the game in Spectrum 48 mode

**Comment by Alessandro1970** [comment]
Ok, loaded from menu in Spectrum 48 mode
