### ISSUE TITLE
Virtual keyboard error

### ISSUE THREAD

**Issue by PakkunKinoppi** [raydac/zxpoly#25]
Hi, if I press a lot of times a key "going out" of the that key while pressing mouse button the keys remain green (marked) like in photo.
Pc Version of zxpoly
![Untitled 2](https://user-images.githubusercontent.com/52820759/114716924-d4dc4e00-9d34-11eb-83a8-ac72a2317016.png)

**Comment by PakkunKinoppi** [comment]
It occours in the default layout too, just pressing a lot of times a key moving the pointer to another one...

![Untitled 2](https://user-images.githubusercontent.com/52820759/114717535-6a77dd80-9d35-11eb-8682-a0e2ada0c8af.jpg)

**Comment by PakkunKinoppi** [comment]
...this is a great zx emulator, I'd like to see it grow up a lot ! THANKS

**Comment by Alessandro1970** [comment]
It does not work for me too, while jumping from a key to another while clicking the mouse (the key remains stuck)

**Comment by Alvarez81** [comment]
It appens to me too, but if you press on the green circle again it turn off.
So you can close them one by one at time.

**Comment by rossimariolee** [comment]
Just press on each one onece more to remove the keys blocked (stuck)

**Comment by PakkunKinoppi** [comment]
Ok, probably this is not a bug. Pressing to fast and moving the pointer can cause it but the emulator does not hang, just press the keycap again to remove the green circle...
