### ISSUE TITLE
Smash Megademo hangs

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#26]
Hi,
this demo stops while loading and does not start.

[Smash Megademo (1996)(ESA).zip](https://github.com/raydac/zxpoly/files/6315347/Smash.Megademo.1996.ESA.zip)

**Comment by raydac** [comment]
I made some changes in SNAPSHOT, try pls

**Comment by Alessandro1970** [comment]
This release is better but the emulator does not stop tape by itself, so to run next parts is needed to rewind tape every time (first time I need to rewind to "smash0")
![gg](https://user-images.githubusercontent.com/34916641/147634018-7d944afa-a69b-45a9-8b67-af49e507de2f.png)

**Comment by raydac** [comment]
it is TAP file, commands for auto-stop provided only by TZX format

**Comment by Alvarez81** [comment]
You can run it without rewind tape ? How ?

**Comment by Alvarez81** [comment]
Is it possible to implement the auto-stop for TAP in ZXPOLY ?

**Comment by raydac** [comment]
there are special commands to stop tape in TZX but TAP contains just headers and data, I don't see way how to implement auto-stop in such case

**Comment by Alvarez81** [comment]
Try to load it in Fuse, it works; there is the way to

**Comment by Haroldo64** [comment]
I have found a tzx version, it works on fuse and on speccy but zxpoly won't load:
[Smash55.zip](https://github.com/raydac/zxpoly/files/7791758/Smash55.zip)

**Comment by Alessandro1970** [comment]
Hi, I have converted Smash.tap in .tzx using MakeTZX (wingui).
It works on fuse but it is not recognized by ZxPoly, Why?

[Smash_conv.zip](https://github.com/raydac/zxpoly/files/7791874/Smash_conv.zip)

**Comment by raydac** [comment]
@Haroldo64 I have tried the TZX, it works, just after screen loading you have to press enter to continue load else it waiting for something

**Comment by Alessandro1970** [comment]
Ok pressing enter (at first step) but after the tape don't' load the right files because it didn'sop and the tapes lose the right file going away (needed to rewind):

> This release is better but the emulator does not stop tape by itself, so to run next parts is needed to rewind tape every time (first time I need to rewind to "smash0") ![gg](https://user-images.githubusercontent.com/34916641/147634018-7d944afa-a69b-45a9-8b67-af49e507de2f.png)

**Comment by Alessandro1970** [comment]
Press 5 to go on after green face, then for see this image in zxpoly you have to rewind tape because the tape is too ahehad.
![ggg](https://user-images.githubusercontent.com/34916641/147740256-4f603772-a403-4859-9f5d-0345fce847ec.png)

**Comment by raydac** [comment]
may be in Fuse it is related to `detect-loader` functionality
```
--detect-loader
    Specify whether Fuse should attempt to detect when the tape is being accessed and start and stop the virtual tape playing automatically. (Enabled by default, but you can use `--no-detect-loader' to disable). Same as the Media Options dialog's Detect loaders option.
```

**Comment by Alessandro1970** [comment]
Auto detect start/stop for tape missing. It is needed to rewind tape in order to continue in loading, then the demo works well.
