### ISSUE TITLE
MQM 5 demo hangs

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#27]
MQM 5 demo hangs after first step, pressing space does not load the second step but hangs.

[MQM 5 (1993)(MQM Team)(128K)(CZ)(en).zip](https://github.com/raydac/zxpoly/files/6315372/MQM.5.1993.MQM.Team.128K.CZ.en.zip)

**Comment by raydac** [comment]
non reproducible with latest snapshot, try in zx-128 mode
