### ISSUE TITLE
Mind Control demo hangs

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#28]
Mind Control demo hangs while loading...
[Mind Control (1999-07)(Crazytronic)[Doxycon].zip](https://github.com/raydac/zxpoly/files/6315524/Mind.Control.1999-07.Crazytronic.Doxycon.zip)

**Comment by raydac** [comment]
could you try it with SNAPSHOT and Amstrad +2 ROM?

**Comment by Alessandro1970** [comment]
It worked for me with 128-zx rom (ubuntu) to but I needed to rewind tape in order to continue in loading it (it does not stop before "minc_1" part) .
The tape does not stop at right time in multiload software.

**Comment by Alessandro1970** [comment]
I have converted to tzx but the auto-stop doesn't work well, because it miss to load the MINC_1 part as you can see in the screenshot (on fuse it works):
[Mind.zip](https://github.com/raydac/zxpoly/files/7791970/Mind.zip)

![fff](https://user-images.githubusercontent.com/34916641/147732297-5bb69bcd-d7fb-41ab-ae28-880a565f9e80.png)

**Comment by raydac** [comment]
my emulator emulates real reading from tape without any magic and traps of subroutines so that you have to be careful with manual stop of TAPE as with real spectrum, may be it would be good in a TZX editor just add tape auto-stop in correct places

**Comment by Alessandro1970** [comment]
it's right.
Could someone tell me the way to add these tape stop ? Which app ?
I

**Comment by raydac** [comment]
as I know there is some application [ZX-Blockeditor](https://zx-modules.de/?page_id=2)

**Comment by Alessandro1970** [comment]
Thaks found....
but what is the "tape-stop"command to put in before the  "minc_1" part ?

**Comment by raydac** [comment]
there is PauseOrStop block in TZX (I don't know how it is called in the utility) and if value for pause is 0 then block recognized as tape stop

**Comment by Haroldo64** [comment]
The demo works fine (manual loading), the problem is that zxpoly does not have the auto detect start / stop for tape files function; this particularity should be implemented.

**Comment by Alessandro1970** [comment]
Auto detect start/stop for tape missing. It is needed to rewind tape in order to continue in loading, then the demo works well.
