### ISSUE TITLE
Z80test fails

### ISSUE THREAD

**Issue by Haroldo64** [raydac/zxpoly#30]
Hi, some z80 cpu tests fail

[z80test-1.0.zip](https://github.com/raydac/zxpoly/files/6389843/z80test-1.0.zip)

**Comment by raydac** [comment]
as I see pair test failed for processing of undocumented flags, I saw it before but still have no idea how to fix, I have added some tests but without success

**Comment by Alessandro1970** [comment]
hi, could you see the source from Fuse ? It passes all z80 tests:

![Untitled 2](https://user-images.githubusercontent.com/34916641/118602958-a0d0ce80-b7b3-11eb-8fec-7c190ab5233c.png)

**Comment by Haroldo64** [comment]
Yes, I have checked them on fuse and on fuse they work.
Something to be implemented in z80 core emulation

**Comment by Haroldo64** [comment]
May these Z80 core files be useful ?

[zilogz80.zip](https://github.com/raydac/zxpoly/files/6500949/zilogz80.zip)

**Comment by PakkunKinoppi** [comment]
Z80 instructions and CCF/SCF XY and others flags aren't fully implemented, if it could be possible to use "fuse cpu source code" it would be better because it works well.

**Comment by raydac** [comment]
I use latest Z80 test from FUSE and it shows that I have only problem with F3/F5 with BIT n, (HL)

**Comment by Haroldo64** [comment]
Hi, any news for a new release ?

**Comment by raydac** [comment]
@Haroldo64 
if you about Z80 core incompatibility then there no news yet, I still can't find place where undocumented flags unexpectedly changed

**Comment by raydac** [comment]
I have fixed Z80 core and now all tests passed like in Fuse
