### ISSUE TITLE
IR_Contention test does not work

### ISSUE THREAD

**Issue by Haroldo64** [raydac/zxpoly#32]
IR_Contention test does not work on 48K spectrum emulation

[IR_Contention.zip](https://github.com/raydac/zxpoly/files/6396912/IR_Contention.zip)

**Comment by raydac** [comment]
I have tried in Spectrum 48 mode, looks working
![image](https://user-images.githubusercontent.com/3008810/121784598-7230f280-cbbd-11eb-95f0-48e52088c996.png)
