### ISSUE TITLE
Loading Snapshot doens't load full state of machine.

### ISSUE THREAD

**Issue by Silveriomrs** [raydac/zxpoly#36]
Good morning,

OS: Linux Mint 20.2

I have check it, when I save a game with no clash colour, etc... in Snapshot and I load it again, it doesn't keep the attributes from the game & machine. I mean, it loads as no special palete and with clash colour.  Like a regular ZX Spectrum with original palete.

Cheers

**Comment by Silveriomrs** [comment]
Sorry,
You're right, but I decided to record a video instead to describe it.

Here is the link, it's a hide video, so only with this link you can see it.
https://youtu.be/v1FWOCF2wEY

When you consider OK just tell me to remove it.

Thanks

**Comment by raydac** [comment]
now I understand, you have loaded Spec256 game and saving it as ZXPoly snapshot
I didn't implement any adaptation because didn't think about such use case, thank you
I will check how to fix it

**Comment by raydac** [comment]
I have made improvements, you can try 2.2.2-SNAPSHOT

**Comment by Silveriomrs** [comment]
![imagen](https://user-images.githubusercontent.com/33696002/139876280-960c2e13-3707-4c47-bdb4-1feea820b92b.png)
Hi, that was the version I tried it out.

**Comment by raydac** [comment]
updated snapshot version can be downloaded from here https://github.com/raydac/zxpoly/releases/tag/2.2.2-S

**Comment by Silveriomrs** [comment]
![imagen](https://user-images.githubusercontent.com/33696002/139878926-a6905c26-6169-48b8-9219-62510b82ed20.png)

It works fine now.
Here is the console log too.

Thanks for your job

**Comment by raydac** [comment]
one explanation that it is not zxpoly mode, it is spec256 mode and spec256 snapshots

**Comment by Silveriomrs** [comment]
Related issue, 
When trying to type the name of the snapshot to save... i cannot delete what was wroten, I mean... trying to get back to correct a typing mistake it doesn't allow, only type new characters not to back.

**Comment by raydac** [comment]
I also saw such behavior under Ubuntu and looks like that it is issue of JDK file chooser panel, I will investigate

**Comment by Silveriomrs** [comment]
I can garantee that not. I use JDK11 and JPanelChooser and it has not that behavior on my projects.

**Comment by raydac** [comment]
do you use for your projects native look and feel?
