### ISSUE TITLE
Saving SnapShot cannot delete (backspace or del key)

### ISSUE THREAD

**Issue by Silveriomrs** [raydac/zxpoly#37]
Saving Snapshot Issue,

When trying to type the name of the snapshot to save... i cannot delete what was wroten, I mean... trying to get back to correct a typing mistake it doesn't allow it, only type new characters not to back, not delete or backspace keys.

**Comment by Silveriomrs** [comment]
Yes, I use native look and feel, actually I didn't change it from Eclipse configuration (metal look and feel).
Note I use LM with Cinnamon desktop.

What could I do to help you to track the issue?

May has it a relation with the JDK version we are using? I only use LT versions. Nowadays 11

**Comment by raydac** [comment]
I have found the bug, you can try 2.2.2-snapshot

**Comment by Silveriomrs** [comment]
Works fine now.
I have checked your code out, I like how you solved it.
Thanks
