### ISSUE TITLE
Virtual keyboard + theme

### ISSUE THREAD

**Issue by Alvarez81** [raydac/zxpoly#38]
Hi, Zxpoly is a 128k Zx Spectrum+ emulator, why cannot be used a virtual keyboard  xSpectrum128 layout ?

This I mean, the rubber version is not so beautiful...
![128k_kbd](https://user-images.githubusercontent.com/39189763/141086401-1eee25a6-8c1a-4b65-a74b-07ca7207785f.jpg)

**Comment by Alessandro1970** [comment]
Oh yes, It will be better.
I prefear the Zx Spectrum plus keyboard than the old rubber one.

**Comment by Haroldo64** [comment]
You are right, the plus virtual keyboard should be better.
If the replacement could be a problem it could be possible to tweak the standard one pasting over it the zxspectrum+ keycaps using the same position. But the design will be more beautifull

**Comment by Alessandro1970** [comment]
@Haroldo64 
Do you mean something about this ?
Replacing key icons...

![Untitled 2](https://user-images.githubusercontent.com/34916641/141098705-bf269f38-4b72-4dcb-ad7a-3370f5785c7b.png)

**Comment by Alessandro1970** [comment]
It will be simple in this way (some keys will be adapted...) but the result is fine.

The Hi-Res picture of ZxSpectrum+ or something is needed, I found only low-res photo...

**Comment by Haroldo64** [comment]
@Alessandro1970 
Yes I do, your solution could be cool !
HiRES keycaps are needed.

**Comment by Alvarez81** [comment]
@Alessandro1970 @Haroldo64 
thanks, so it's great ! I like it if the keys will be in high definition.

**Comment by Alessandro1970** [comment]
Hi @raydac 

I have made this theme for ZxPoly, If you look ok, could you add to the project ?
Symbols and tokens are set like in the zx48k version.

SVG:
[AmbroZxPlusKB_SVG.zip](https://github.com/raydac/zxpoly/files/7587950/AmbroZxPlusKB_SVG.zip)

PNG:
![AmbroZxPlusKB](https://user-images.githubusercontent.com/34916641/143024332-7d9a0020-8c0b-4c19-859b-2624355a2329.png)

**Comment by raydac** [comment]
great! thanks a lot @Alessandro1970 
I have added the skin and you can try snapshot

**Comment by Alessandro1970** [comment]
Thank you
