### ISSUE TITLE
New Timex-like skin for ZxPoly

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#39]
Hi, @raydac 
I have built this one, if you like you can add to the project.

Bye

[AmbroTimexKB.zip](https://github.com/raydac/zxpoly/files/7633421/AmbroTimexKB.zip)

![AmbroTimexKB](https://user-images.githubusercontent.com/34916641/144227616-0d5f6b29-0dc8-4ae6-848f-4b83dad87656.png)

**Comment by raydac** [comment]
Great! Thank you! I have added it into snapshot, you can take a look

**Comment by Alvarez81** [comment]
hi @raydac there is a "N" missing in your one [ASN]:

![asn](https://user-images.githubusercontent.com/39189763/144391718-205ac23e-19c6-4293-98ae-dfde186e07aa.png)

**Comment by raydac** [comment]
ok thanks @Alvarez81
