### ISSUE TITLE
Virtual Keyboard

### ISSUE THREAD

**Issue by Haroldo64** [raydac/zxpoly#4]
Hi, thaks for this great emulator in java ...harder to find something good in java

I think that for some compatibility problem with modern keyboard would be fine to implement a virtual keyboard with sinclair tokens to use with mouse ...point and click to select basic commands and sticky key for caps lock etc (like virtual keyboard on this emulator https://www.emutopia.com/index.php/emulators/item/364-sinclair-zx-spectrum/253-unreal-speccy-portable)

Thanks 
bye

**Comment by raydac** [comment]
I have implemented some virtual keyboard, now the on-screen keyboard shown by F5 pressing is clickable by mouse, take a look pls https://github.com/raydac/zxpoly/releases/tag/2.1.3-S

**Comment by rossimariolee** [comment]
Hi, great job.
A Virtual keyboard is very useful.

Is it possible to put the virtual keyboard on a floating windows (out the output the emulator window) to see all what is tiped in ?

thank you 
bye

**Comment by Haroldo64** [comment]
...oh yes, the virtual keyboard out of the output screen would be nice !
Great emulator!
Thanks

**Comment by Alessandro1970** [comment]
Hello, 
thank you for this great emulator. 
The possibility to use the keyboard on a floating window out of the output screen would be a great goal.
Is there the possibility to have a Apple Silicon Universal App ?

Bye

**Comment by raydac** [comment]
@Alessandro1970 
I have no idea what is  Apple Silicon Universal App

**Comment by Alessandro1970** [comment]
The new "Universal 2" binaries contain architectures slices compatible with Intel and Apple Silicon (M1 Arm CPU).

**Comment by raydac** [comment]
@Alessandro1970 
I am not sure that it will be possible for me to make some very complex solution (I am not a mac user and use some simple platform emulation for tests), but looks like that it is very good idea to start providing and ARM version for Apple platform

**Comment by Haroldo64** [comment]
Thank you, but could you put the virtual keyboard under the output screen ?
I cannot see what I'm typing with the virtual keyboard in front of.

**Comment by raydac** [comment]
@Haroldo64 
I made some changes in snapshot and now you can select to see virtual keyboard in as apart window, it is selectable through preferences (restart required)

**Comment by Alessandro1970** [comment]
Thank you, now the Virtual Keyboard is fully usable !
