### ISSUE TITLE
TZX Loading error

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#40]
Hi,
here they are some Tzx files that don't run for me on ZxPoly:
[Enigma force [48-128K].zip](https://github.com/raydac/zxpoly/files/7703122/Enigma.force.48-128K.zip)
[Bionic Commando [48-128K].zip] **damaged tape**
[Elite [128K].zip](https://github.com/raydac/zxpoly/files/7703129/Elite.128K.zip)
[Exolon [48-128K].zip](https://github.com/raydac/zxpoly/files/7703131/Exolon.48-128K.zip)
[Cobra [48K].zip](https://github.com/raydac/zxpoly/files/7703136/Cobra.48K.zip)
[Ghosts Goblins [48-128K].zip](https://github.com/raydac/zxpoly/files/7703138/Ghosts.Goblins.48-128K.zip)
[Gryzor [128K].zip](https://github.com/raydac/zxpoly/files/7703141/Gryzor.128K.zip)
[Anogaia [48-128K].zip](https://github.com/raydac/zxpoly/files/7703143/Anogaia.48-128K.zip)
[Cattivik 1 [128K].zip](https://github.com/raydac/zxpoly/files/7703145/Cattivik.1.128K.zip)
[Camelot Warriors [48K].zip](https://github.com/raydac/zxpoly/files/7703146/Camelot.Warriors.48K.zip)

Bionic Commando tzx: 
[Bionic Commando (1988)(Go - Capcom)(128k).zip](https://github.com/raydac/zxpoly/files/7710392/Bionic.Commando.1988.Go.-.Capcom.128k.zip)

Bye

**Comment by raydac** [comment]
I have fixed it in snapshot

**Comment by Alessandro1970** [comment]
Near the keyboard icon could be good two buttons: one for start tape and one for stop tape ...some games need to stop tape at some point

**Comment by Alessandro1970** [comment]
For Camelot warriors the same problem is in the z80 file, it run on fuse but hangs at the same point in Zxpoly
[Camelot Warriors (1986)(Ariolasoft UK).zip](https://github.com/raydac/zxpoly/files/7710478/Camelot.Warriors.1986.Ariolasoft.UK.zip)

**Comment by raydac** [comment]
I have tried Cobra TZX in 128k mode (with latest SNAPSHOT), it works but looks like that TZX has too short pauses and I have to rewind tape to cobra block during loading after loader inited

**Comment by raydac** [comment]
I have added auto-stop support in snapshot version

**Comment by Alessandro1970** [comment]
Game fixed downloaded, all is working fine.
