### ISSUE TITLE
Some games TZX format do not work

### ISSUE THREAD

**Issue by Alvarez81** [raydac/zxpoly#41]
These games work on fuse but don't run on ZXPOLY

[Switchblade.zip](https://github.com/raydac/zxpoly/files/7704163/Switchblade.zip)
[Great Escape.zip](https://github.com/raydac/zxpoly/files/7704075/Great.Escape.zip)
[Magick.zip](https://github.com/raydac/zxpoly/files/7704076/Magick.zip)
[Stormbringer.zip](https://github.com/raydac/zxpoly/files/7704098/Stormbringer.zip)
[Zynaps.zip](https://github.com/raydac/zxpoly/files/7704143/Zynaps.zip)
[Uridium.zip](https://github.com/raydac/zxpoly/files/7704182/Uridium.zip)
[Mask.zip](https://github.com/raydac/zxpoly/files/7704147/Mask.zip)
[Runestone.zip](https://github.com/raydac/zxpoly/files/7704149/Runestone.zip)

Loading error:
![sw](https://user-images.githubusercontent.com/39189763/145820137-0dc56c52-052a-4221-b5ad-915f3b5d3f3d.png)
![game](https://user-images.githubusercontent.com/39189763/145819753-5218d57d-19fa-4a68-b956-2ed3e85f84b4.png)

**Comment by raydac** [comment]
I have fixed in snapshot but some games loading with error

**Comment by Alessandro1970** [comment]
With new release only these do not work:

Mask.zip [Only in 48k mode but it does not work nor on Fuse 1.6]
Runestone.zip [run only  in 48k mode on fuse]

**Comment by raydac** [comment]
interesting, managed to start Runestone downloaded from https://www.alessandrogrussu.it/plus2A-en.html

**Comment by Alvarez81** [comment]
Hi, MASK and Runestone works well for me in my Mister FPGA that implements and recreates the orginal ULA and timings for the 128K.
So the bugs are in the Ula emulations ...Camelot Warrios too ?

**Comment by Alessandro1970** [comment]
...camelot warriors too: yes !
Can be read here : https://www.spectrumcomputing.co.uk/forums/viewtopic.php?f=21&t=697
The solution is to "normalize" ULA support in ZxPoly to have the same performances of the 128k original ULA

**Comment by Alessandro1970** [comment]
Here it is the Camelot Warrios working well for ZxPoly !
[Camelot Warriors (1986)(Ariolasoft UK)[re-release] (Fixed by Ast A. Moore).zip](https://github.com/raydac/zxpoly/files/7717605/Camelot.Warriors.1986.Ariolasoft.UK.re-release.Fixed.by.Ast.A.Moore.zip)

Fixed

**Comment by Alessandro1970** [comment]
...and this release of Runestone works well with ZxPoly:
[Runestone.zip](https://github.com/raydac/zxpoly/files/7718200/Runestone.zip)

**Comment by Alvarez81** [comment]
Ok, now they works well
thanks
