### ISSUE TITLE
Lone Wolf 3 tzx does not run

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#42]
Hi, I cannot succeed in loading this game.
[LoneWolf-TheMirrorOfDeath(System4).tzx.zip](https://github.com/raydac/zxpoly/files/7740511/LoneWolf-TheMirrorOfDeath.System4.tzx.zip)

or this release
[LoneWolf-TheMirrorOfDeath.tzx.zip](https://github.com/raydac/zxpoly/files/7740512/LoneWolf-TheMirrorOfDeath.tzx.zip)

**Comment by raydac** [comment]
TZX format is very specific one and very depends on converter which was in use to grab tape so that it would be  good to recognize as an error in emulator if TZX back converted in WAV (for instance by tape2wav) can be downloaded by emulator and the same TZX file shows different behavior

**Comment by Alessandro1970** [comment]
Neither the tap works.
I diwnloaded files here:
https://spectrumcomputing.co.uk/index.php?cat=96&id=2920

**Comment by raydac** [comment]
it's interesting that fuse also had some problems with the game as I see in [the thread](https://sourceforge.net/p/fuse-emulator/bugs/352/) and there is [link for working version](https://www.dropbox.com/s/6zy8ocucs0okm1a/Lone%20Wolf%20-%20The%20Mirror%20of%20Death%20-%20Audiogenic%20-%20V1.zip)

**Comment by Alessandro1970** [comment]
Thanks for the working version link.
