### ISSUE TITLE
Menu bar more buttons

### ISSUE THREAD

**Issue by Alvarez81** [raydac/zxpoly#43]
Could you add other three buttons on the menu bar near the keyboard and pause ?
One button for Turbo Mode (F3 oprtion) and one button for ZxKeyboard ON/OFF (F6 option) and last button for force reset (F12 option).

Thanks
bye

**Comment by PakkunKinoppi** [comment]
Hi, this would be a fine add-on, but it would be better if everyone culd add the buttons that are needed and place them from left to right freely...

**Comment by raydac** [comment]
@Alvarez81 what value will it bring if it is already accessible through hot keys?

**Comment by PakkunKinoppi** [comment]
Icons on menu bar are selected faster for many mac users that have to press more than one key to turn on Functions Key would be better !
I use often turbo for loading...

**Comment by raydac** [comment]
I have added configurable fast buttons, they can be added on menu bar through pop-up menu over the menu bar, you can try snapshot 2.2.3

**Comment by Haroldo64** [comment]
Thanks fine, but the first two (Keyboard and pause) are blocked in the menu.I cannot deselect them.

**Comment by Alessandro1970** [comment]
Thank you for the turbo button on the bar !!!

**Comment by raydac** [comment]
@Haroldo64 
I still think is it good idea or not to provide way to remove them, because there are not menu items to turn on/off start/pause emulator and virtual keyboard

**Comment by Haroldo64** [comment]
Ok, no problems.

The turbo button on the bar is very usefull, thank you.

**Comment by raydac** [comment]
if any ideas which buttons to add in the fast button list then welcome

**Comment by Alessandro1970** [comment]
Reset button

**Comment by Haroldo64** [comment]
Reset and Soun on/off

**Comment by rossimariolee** [comment]
Reset

**Comment by Alvarez81** [comment]
Reset button for me too

**Comment by raydac** [comment]
you can try SNAPSHOT

**Comment by Alvarez81** [comment]
Thank you
