### ISSUE TITLE
ZxDiagnostic test hangs

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#44]
Hi, the ZxDiagnostic test hangs, is there a solution ?

[Diagnostic.zip](https://github.com/raydac/zxpoly/files/7773122/Diagnostic.zip)

This is a Fuse screenshot in 128K mode:
![Untitled 1](https://user-images.githubusercontent.com/34916641/147328732-ef8ae294-a4a6-417a-9efc-9b800eb1fbf1.png)

**Comment by raydac** [comment]
as I see the test starts but can't detect pressed key in ZX128 mode and trying to start in ZX48 after delay, I have sent question to the author of the test

**Comment by raydac** [comment]
I have added new ROM sources into SNAPSHOT, if select one of standard ZX128 ROM  (like Amstrad +2 or Spanish or 128 without TRDOS) then the application works well
