### ISSUE TITLE
AmbroZxPlusKB_SVG Revision

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#46]
Hi @raydac 
I have updated the keyboard theme AmbroZxPlusKB_SVG, corrections were needed.

Could you upload the file and add it to the project, please ?

Last revision:
[AmbroZxPlusKB_SVG.zip](https://github.com/raydac/zxpoly/files/7780183/AmbroZxPlusKB_SVG.zip)

![FFFF_2](https://user-images.githubusercontent.com/34916641/147470193-5a0ed671-117c-4f3d-8bd0-3ebca99033e2.png)

**Comment by Haroldo64** [comment]
Thank you

**Comment by Alessandro1970** [comment]
Thanks

**Comment by Alvarez81** [comment]
This theme is really great, I'll use this from defautl.
Thak you, I remainds me to my old Spectrum+
