### ISSUE TITLE
Vibrations Demo Hangs

### ISSUE THREAD

**Issue by Alvarez81** [raydac/zxpoly#47]
This demo hangs and zxpoly stops with a green screen after few seconds and few flying writings:
[Vibrations.zip](https://github.com/raydac/zxpoly/files/7780480/Vibrations.zip)

![hh](https://user-images.githubusercontent.com/39189763/147478950-f8aed206-a906-4db2-bd12-d9d4b3c2fbe1.png)

**Comment by Alessandro1970** [comment]
There is a problem while loading the tap, but after creating a snapshot from fuse it starts and work for two or three steps after them it hangs again (graphics errors).
[Vibration from fuse snapshot.zip](https://github.com/raydac/zxpoly/files/7784988/Vibration.from.fuse.snapshot.zip)

![1111](https://user-images.githubusercontent.com/34916641/147573568-51018cce-5d2e-437d-a510-35c6f5130688.png)

**Comment by Alvarez81** [comment]
Just loaded in 48K mode, :hear_no_evil: 

It's another demo, better in 128K mode. This is really a demo !

**Comment by Alessandro1970** [comment]
I have ### written **do not load in 48k mode** ! :laughing:  :rofl:

**Comment by raydac** [comment]
I made some improvements, please try SNAPSHOT
