### ISSUE TITLE
Keyboard theme and graphic grid error

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#48]
@raydac 
Sorry but there were some wrong lines in the graphic grid.
I have updated the SVG:
[AmbroTmxPalKB.zip](https://github.com/raydac/zxpoly/files/7783394/AmbroTmxPalKB.zip)

![wAmbroTmxPalKB6](https://user-images.githubusercontent.com/34916641/147540135-3657e3e4-463c-4643-bf67-2ea2f4c86beb.png)

**Comment by rossimariolee** [comment]
Fine theme, never seen this spectrum clone

**Comment by Alvarez81** [comment]
Yes very fine, but were metallic the keycaps ?

**Comment by Alessandro1970** [comment]
Plastic keycaps
![uieWwA6](https://user-images.githubusercontent.com/34916641/147542726-c827ae3f-74cb-48b6-ae9a-86a1f9a33a11.png)

**Comment by Alvarez81** [comment]
Thank you, very fine !

**Comment by Alessandro1970** [comment]
Thank you
