### ISSUE TITLE
ESI Demo hangs

### ISSUE THREAD

**Issue by Haroldo64** [raydac/zxpoly#49]
Hi, Esi Demo hangs too, but this is not multi-load. It hangs when it ends the last loading (48k mode).
[ESI_DEMO.zip](https://github.com/raydac/zxpoly/files/7788160/ESI_DEMO.zip)

https://worldofspectrum.org/archive/software/demos/esi-demo-

![bvf](https://user-images.githubusercontent.com/53178600/147647963-40cf4325-e9e2-4244-b603-bdb98ae57dc9.png)

**Comment by raydac** [comment]
I have tried with SNAPSHOT, it doesn't hang just waiting any key press and start as I see

**Comment by Haroldo64** [comment]
Which configuration ?

I waited for 20 minutes and it remains as the image before (i'm using last snapshot 2.2.3 and zx mode - rom zx 128 trdos)

**Comment by raydac** [comment]
have you pressed enter after loading end?

**Comment by Alessandro1970** [comment]
Why press enter ?
On fuse it starts by itself

**Comment by raydac** [comment]
as I know FUSE has many internal hacks for tape loading to automate process may some one of them but as I see the demo not hangs just waiting some press key

**Comment by Haroldo64** [comment]
It's stange but you are right, no message or other only press enter.
