### ISSUE TITLE
Indicator panel

### ISSUE THREAD

**Issue by rossimariolee** [raydac/zxpoly#50]
hi, if I turn off the indicator panel (I do not need this) when I reboot the emulator after closing it turn on automatically.
Is there the way to save settings with the indicator panel off ?

**Comment by raydac** [comment]
at present I don't save state of the panel, going to add such feature

**Comment by raydac** [comment]
you can try SNAPSHOT

**Comment by rossimariolee** [comment]
It works fine.
Thank You !
