### ISSUE TITLE
Roms path

### ISSUE THREAD

**Issue by Alvarez81** [raydac/zxpoly#52]
1) Once downloaded the roms from the preferences, where are they stored (path) ?

2) Please, other the path could you show me the links where are stored the roms on https://vtrd.in/ or Archive.org ? 
I cannot succeed in finding the 128k+TRDOS (how can join them in only one file)

Thank you

**Comment by raydac** [comment]
check application settings folder appropriate for your system and find there folder .zxpolyemul/cache, there should be a rom file named loadedfrom_<hash>.rom
ROM file is merged ROM pages in order Basic128+Sos48[+TrDos]

**Comment by Alvarez81** [comment]
:+1: 
Thank you ...done it !

**Comment by Alessandro1970** [comment]
I cannot find it in mac os
There is not in library or application support dir. where is it stored ?
