### ISSUE TITLE
128 rom path - mac os

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#53]
Hi, I cannot find the path for place bootstrap.rom on mac os.
There is nothing in library, preferences nor library/appdata. 
Where are stored downloaded roms in mac os?
Bye

**Comment by Alessandro1970** [comment]
Found it
It is not stored in common Library/AppsDataSupp or Library/Preferences
In a dedicated folder as like in macos
It can be found out in User/nameuser main directory as a hidden folder named .zxpoltemul

it would be better store .zxpolyemul dir in Users/nameuser/Library/Preferences

**Comment by raydac** [comment]
Java provides the path for its applications, it's different for OSes and if I start play with it then it can break cross-platform work of the application
