### ISSUE TITLE
Bootstrap.rom

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#54]
Where can be placed the bootstrap.rom in mac os ?

Into main app does not work.
In the downloade rom folder it is ignored (.zxpolyemul)
If i place the bootstrap.rom in cache downloaded on a pc it works but on mac it is ignored. 
if I create a folder and I put in zxpoly beside the bootstrap.rom it does not work

**Comment by Alessandro1970** [comment]
I think that bootstrap.rom should be selected from zxpoly preferences panel (like open a game) in this way zxpoly would succeed in finding the rom.

**Comment by raydac** [comment]
custom ROM file path definition doesn't work on Mac?
![image](https://user-images.githubusercontent.com/3008810/147849283-767b3814-3e3f-4753-9532-d15866745880.png)

**Comment by Alessandro1970** [comment]
No it does not work in anyway
Instead if this a selection button would be better to locate file

**Comment by raydac** [comment]
I have added button to select custom bootstrap rom file in preferences panel , try please

**Comment by Alessandro1970** [comment]
Great!
It worked on my old mac intel and on my new mac apple silicon.
Thank you
