### ISSUE TITLE
Open file or snapshot or disk does not find files to load

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#55]
Hi,
I cannot load files, disk or snapshot from open dialog windows on mac.
It seems that Zx poly does not see any files or folder (see photo).
I granted zxpoly to access files from settings but it does not find anything neither folders.
Before I used only drag an drop that works.
![DB83EDD6-4C89-4514-BB84-7C9EC5D43F82](https://user-images.githubusercontent.com/34916641/147871795-8f8e7cc3-ef0d-4644-984d-d45d4f37e536.jpeg)
![BA5EC161-D169-4E7E-8829-FAFF09FD4725](https://user-images.githubusercontent.com/34916641/147871804-43c13651-c950-4a50-abd2-c3c87e0304f1.jpeg)

**Comment by Alessandro1970** [comment]
ZxPoly doesn’t succeed in finding some directories.
I have moved my zx games directory out of Documents and zxpoly succeed in finding games.
If I move the gamesdir to documents or desktop folder again no files were found.
Zxpoly cannot access all directories on macos.

**Comment by raydac** [comment]
as I understand it is related to some Java restrictions by default, I am not a Mac user but [I saw some article about it](https://macperformanceguide.com/blog/2020/20200119_1427-macOS-Catalina-add-java-fullDiskAccess.html)

**Comment by raydac** [comment]
also it very depends on how you start application because it can legacy rights of starter

**Comment by rossimariolee** [comment]
For MacOs I have moved the zx applications and games folder in the user directory (not in subfolder, just right in the User Directory); in this way it works:
**Users/nameuser/zx_Games**

**Not in** : Users/nameuser/Documents/Games, Usersnameuser/Desktop or other similar

**Comment by Alessandro1970** [comment]
**Users/nameuser/ZxSpectrum**
Yes, I have done in such way, so I can open or save everything from ZxPoly.
:+1:
