### ISSUE TITLE
Simulate NMI button

### ISSUE THREAD

**Issue by PakkunKinoppi** [raydac/zxpoly#56]
Hi, I have loaded this .rom in ZxPoly, in order to start it a NMI button has to be pressed.
Is there any way to simulate a NMI button ?

Rom: 
[hdt-iso.zip](https://github.com/raydac/zxpoly/files/7839268/hdt-iso.zip)

Rif:
The build in monitor can be invoked over NMI, the following options are available in the monitor:

1 - switch between HEX/DEC (display and input)
2 - switch between byte/text display of the memory content
3 - load the flashing stack or register
4 - load the top memory cell
5 - memory display -64
6 - memory display -1
7 - memory display +1
8 - memory display +64
9 - stack and register choice -1
0 - stack and register choice +1

symbol shift and 7 - the entered address will be processed as assembler CALL.
                     At the end (1. RET) the program returnes to the monitor.
                     Register contents are not considered!
symbol shift and 8 - makes a relative safe jump to the BASIC editor (#1303)
symbol shift and 9 - executes a RST 8 (error output) and after that to the
                     editor
symbol shift and 0 - executes a RET, continues at the point where the actual
                     program was interrupted by a NMI pulse (if the pulse was
                     short enough). The address to continue is displayed at the
                     top of the stack column.
SPACE              - enter a byte in the actual memory cell
RESET              - warm start
CAPS and RESET     - cold start

The BASIC improvements are:

The cursor keys (6 and 7) can also used by editing in the line.
#nnnn - edit line with number nnnn
-     - switch to higher baud rate
+     - switch to lower baud rate
)     - switch off the display of the three 2-byte numbers in the header
(     - switch on the display of the three 2-byte numbers in the header
*     - call the build in monitor from basic
,     - display the free memory for about 5 seconds

**Comment by PakkunKinoppi** [comment]
This is the same, for insert pokes a NMI button must be pressed.
[POKEAROM.zip](https://github.com/raydac/zxpoly/files/7839377/POKEAROM.zip)


_When the .tap has loaded, and you want to poke
something, press **NMI button**, a blue rectangle
appears upper right. Type 5 numbers (the address)
and enter. Then the value of the address apears.
If you dont change it and press enter the program
returns. If you change it and press enter, the
value of the next adress apears. To return press
enter without changing the value._

**Comment by Haroldo64** [comment]
...another button to be added in the **Menù Bar**

**Comment by raydac** [comment]
I have added emulation of MAGIC button, you can try

**Comment by PakkunKinoppi** [comment]
Great ! It Works well !

thank you !!!
