### ISSUE TITLE
Virtual keyboard skin

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#57]
Hi, @raydac
I have built this one, if you like you can add to the project.

[AmbroCLEANKB.zip](https://github.com/raydac/zxpoly/files/7870326/AmbroCLEANKB.zip)

Bye
![AmbroCLEANKB](https://user-images.githubusercontent.com/34916641/149516084-30b42d4c-9599-42df-8b3f-f7679fdf77b2.png)

**Comment by raydac** [comment]
added into snapshot version

**Comment by Alessandro1970** [comment]
Thank you
