### ISSUE TITLE
Look and feel customization

### ISSUE THREAD

**Issue by Haroldo64** [raydac/zxpoly#58]
Hi,
is there any way to import different "look and feel" themes ?
Where are they located in the SRC ?
![Untitled 2](https://user-images.githubusercontent.com/53178600/149726879-2028c51e-05a3-4a95-8c6d-ac95ae2920e3.png)

**Comment by raydac** [comment]
it is set of look and feels provided by java for host platform, it is possible make some custom l&f and provide in class-path but very hard work

**Comment by Haroldo64** [comment]
I have found nothing news about these themes or how to add more themes.
