### ISSUE TITLE
Something wrong in the graphics of Illusion DEMO

### ISSUE THREAD

**Issue by Haroldo64** [raydac/zxpoly#59]
Hi, something is no painted in the screen or there is a black rectanguar area that is wrong in this part of the demo.
The dot field is partially missing:
[ILLUSION.zip](https://github.com/raydac/zxpoly/files/7897861/ILLUSION.zip)

![ggyg](https://user-images.githubusercontent.com/53178600/150151021-31fa068e-b09e-4971-a01e-82a343aaa21d.png)

![Untitled 4](https://user-images.githubusercontent.com/53178600/150151032-43cc7a59-af27-453e-8841-5d57bf287e56.png)

**Comment by Alessandro1970** [comment]
The usual problem is seen in a later part, as in the photo the small balls are not seen moving in the part above the spiral, my be the ULA ?
![Untitled 2](https://user-images.githubusercontent.com/34916641/150286533-a015cfb8-ef39-4365-be12-adf6e887de5b.png)

**Comment by Alessandro1970** [comment]
...even shortly thereafter, it should be the usual cause, the usual bug:
![Untitled 4](https://user-images.githubusercontent.com/34916641/150287127-65ee80a2-a0db-4fda-b3df-f029840f6664.png)

**Comment by Alessandro1970** [comment]
...mmmm
![Untitled 9](https://user-images.githubusercontent.com/34916641/150289329-6323d5ee-4b6b-4c25-9959-1692821d40f0.png)

But this parts works well even if there is no Pentagon !

**Comment by raydac** [comment]
looks like that problem in some desync between paint and emulator screen blink (emulator written in Java and it accumulates all changes in some off-screen image and draw it by command), I have added some configurable offset for screen blink, you can try snapshot 2.2.4

**Comment by Alessandro1970** [comment]
Great, it works well. 
there is a strange black square on the right, but it's very better, better tha fuse on last demoball.

On my Mac armcpu:
![Untitled 2](https://user-images.githubusercontent.com/34916641/150335438-74420e51-9634-4b97-aa9a-fb5d3d953bcb.png)

**Comment by raydac** [comment]
I guess it is possible to select better screen blit tact in preferences (requires restart) to fix it, the default value I found mainly heuristically

**Comment by Alessandro1970** [comment]
I can see all the little balls, as in screenshot, only if I set blink frame to 23,333, but the the others don't work:
![ee](https://user-images.githubusercontent.com/34916641/150632235-c96201a5-0e83-4468-a3e2-aec2a331719e.png)

**Comment by Alvarez81** [comment]
_Blink frame 38,007
Important is that INT/frame = 1 this takes an important role with BLINK, if int/frame is more than 1 in gryzor you will not see flashing stars and Illusion demo will not work !!!_

This works quite good for me too.

**Comment by Alessandro1970** [comment]
...don't' ask me why 38,007 !
I have tried so many times, probably there will be a better value.

**Comment by PakkunKinoppi** [comment]
I used:

> Blink frame 38,007
Important is that INT/frame = 1 this takes an important role with BLINK, if int/frame is more than 1 in gryzor you will not see flashing stars and Illusion demo will not work !!!

These are good for me too ! Thanks

**Comment by Alvarez81** [comment]
Hi, is there any news ?
I saw that something in the code is changed...

**Comment by raydac** [comment]
@Alvarez81 
not yet, I am trying to make emulation of correct timing but without big success yet

**Comment by Alvarez81** [comment]
Ok, something about timings was found here, but I do not know if this could help about:
http://www.zxspectrum4.net/op_timing.php
http://www.zxdesign.info/memContRevision.shtml
https://scratchpad.fandom.com/wiki/Contended_memory#Timing_differences
Bye
...we like a lot your ZxPoly !

**Comment by raydac** [comment]
I made some rework of render and you can try snapshot, the problem with demos that they are oriented to TV and expecting that we have ray-tracing so that they dynamically changing already TV-rendered area during the same frame and I render screen in the end of frame
I have removed blink tact parameters and replaced by timing profile chooser

**Comment by Haroldo64** [comment]
Great it works well, thank you.
