### ISSUE TITLE
Terra Cresta Game hangs at start

### ISSUE THREAD

**Issue by Haroldo64** [raydac/zxpoly#6]
Hi,
after loading the game, it hangs at title screen, in other emulators pressing space bar the game starts.

[game.zip](https://github.com/raydac/zxpoly/files/5988658/game.zip)

**Comment by raydac** [comment]
IFF flag in the Z80 snapshot is reset so that keyboard doesn't work after download, interesting why other emulators can process it (in such situation it is also possible just open service->trace window for CPU0 and press button "set IFF1"

**Comment by raydac** [comment]
tried the game under FUSE emulator, it also hangs after load

**Comment by Alessandro1970** [comment]
..on the speccy of Marat it works
![Untitled 2](https://user-images.githubusercontent.com/34916641/108067587-4d8a9b00-7061-11eb-9404-02984fe14ded.jpg)

**Comment by Alessandro1970** [comment]
[game_2.zip](https://github.com/raydac/zxpoly/files/5988804/game_2.zip)

I made this z80 from the Speccy, so you can load in ZxPoly.
But the fire (kempston) does not works for me [I have selected first "Z" then "X" as fire from preferences but didn't work

**Comment by Alessandro1970** [comment]
Two buttons for kempston, split instead fire ?

**Comment by raydac** [comment]
looks like that the game just not like if you select any alpha key which also playing role in zx keyboard (may be some internal check for keyboard press during game blocking file on kempston), if select 0 or 1 as kempston fire then works well

**Comment by Alessandro1970** [comment]
Ok, "1" works as FIRE button.
It's strange...

**Comment by raydac** [comment]
it is not strange because if you trying to share keyboard in same time between kempston and zx keyboard (I mean keys playing in both cases) then you can get such effects because a game can be developed for mode when  kempston joystick recognized as  absolutely external device without duplication on zx keyboard, for such reasons by default kempston is mapped to numpad keys

**Comment by Alessandro1970** [comment]
:cry:  ..on Mac Book Pro we haven't the Numpad keys...

**Comment by raydac** [comment]
also emulator supports joysticks so that if you like play with joystick you can just use any usb-gamepad
