### ISSUE TITLE
Vampire Vengeance Tap not recognized

### ISSUE THREAD

**Issue by Alvarez81** [raydac/zxpoly#60]
Hi, this .tap is not recognize as in fuse or other.
[VampireVengeance.tap.zip](https://github.com/raydac/zxpoly/files/7968735/VampireVengeance.tap.zip)

![bbb](https://user-images.githubusercontent.com/39189763/151751665-83501fc9-34c9-40eb-9bf7-dabd4358f4c1.png)

**Comment by raydac** [comment]
I have improved TAP file reader, you can try SNAPSHOT

**Comment by Alvarez81** [comment]
It does not run:
![Untitled 1](https://user-images.githubusercontent.com/39189763/152111007-55b8a8b7-1b17-45bd-a986-a380e74e2fc8.png)

**Comment by raydac** [comment]
I have updated SNAPSHOT

**Comment by Alvarez81** [comment]
Thank you
