### ISSUE TITLE
Save a new .tap file

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#62]
Hi, is there the possibility to save a Basic Program like in the image to a new .tap or .tzx file ?

![Untitled 2](https://user-images.githubusercontent.com/34916641/152311131-c055160d-8e4f-4116-ba86-65fca5604a87.png)

**Comment by raydac** [comment]
at present it is not supported, may be I will add feature to save TAP signal as WAV

**Comment by raydac** [comment]
I have added feature to write emulator sound as WAV file so that you can save basic programs through the WAV file. Toggle button "Service->Record WAV" or fast button "Start/stop record WAV", you can try snapshot

**Comment by Alessandro1970** [comment]
It works well.

Thank You

**Comment by Alvarez81** [comment]
thanks
