### ISSUE TITLE
Cannot save permanently on disk (TRDOS)

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#64]
Hi,
I have formatted a TRDOS Disk then I have saved a file and verified it by CAT command.
If I quit ZxPoly after restarting the changes on that disk are lost, is there any possibilities to export changes saving the disk or something other to make permanent those changes ?

Thanks

**Comment by raydac** [comment]
emulator will show dialog about non saved disk changes and you can flush them into file through press the button in the dialog
![image](https://user-images.githubusercontent.com/3008810/152368810-b9e51fe4-32d4-4cfa-9073-4c71f4aef2ca.png)

**Comment by Alessandro1970** [comment]
Ok, it worked, thanks

**Comment by raydac** [comment]
I have improved SNAPSHOT, now it makes pre-formatted TRDOS disks

**Comment by Alvarez81** [comment]
Where is the command to create new disks ?

**Comment by raydac** [comment]
when you select trdos disk then you can enter name of non existing file and it will be created as pre-formatted trd

**Comment by Alvarez81** [comment]
Ok, no so intuitive for all of whom that haven't read this.
Could be added a command in the first menu' befor **Load Disk** ?
**Create TR-Dos Disk**

So all of us and the future users could be use it easy

**Comment by Alvarez81** [comment]
Something of this:
![Untitled 3](https://user-images.githubusercontent.com/39189763/152516035-94534c4d-cced-4b22-af34-d1f72cbe8c2f.png)

**Comment by raydac** [comment]
I think it is good idea to add explicit command to create TRD disk

**Comment by Alvarez81** [comment]
Your is a great emulator, should be known and used by many people for the noumerous assets.
Great z80 compatibility, great virtual keyboards.
...some improvments in the menu' and in ULA compatibility than it will be a great goal !

**Comment by Alessandro1970** [comment]
Certainly ZxPoly is and will be a great and very versatile emulator.
I really like it a lot and for some time now it's the only ZxSpectrum emulator that I use on both Mac and PC.
At this point, if the two tests you have put (Timing_Tests-48k and Woody's Special) will be satisfied, I think the emulator will be really mature and robust.
Who knows what it would have been like if it was released from java and reprogrammed only in C / C ++with other related benefits and speed of code...

**Comment by raydac** [comment]
I have added in SNAPSHOT, new file menu item "Create empty disk"
