### ISSUE TITLE
Zilog DMA Test fails

### ISSUE THREAD

**Issue by Haroldo64** [raydac/zxpoly#65]
This test doesn't work well on zxpoly, upper border is black and other parameters are wrong:
[zilogdma.zip](https://github.com/raydac/zxpoly/files/8013483/zilogdma.zip)

On fuse:
![fff](https://user-images.githubusercontent.com/53178600/152750667-cc28ad36-cb4a-4f23-825e-62fb7707fe56.png)

**Comment by PakkunKinoppi** [comment]
Sorry. I do not understand this test, what is wrong and why ?

**Comment by Alessandro1970** [comment]
ZxPoly vx Speccy (the parameters seem to be the same, only the border !?)
![Untitled 5](https://user-images.githubusercontent.com/34916641/153362503-00c5ec94-a5ed-4892-bbc1-76f5948dc841.jpg)

**Comment by Alessandro1970** [comment]
As written on the test screen the upper border should be yellow (?), press P on ZxPoly [it works !]:
![Untitled 2](https://user-images.githubusercontent.com/34916641/153363194-c5ece0f1-1875-41ba-b630-6d417f2902a2.png)

**Comment by Haroldo64** [comment]
Sorry, I thought this was a wrong test
