### ISSUE TITLE
Virtual keyboard skin Zx81 Style

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#66]
Hi, @raydac
I have built this one like vintage Zx81 keys, if you like you can add to the project.

[AmbroZX81STYLE.zip](https://github.com/raydac/zxpoly/files/8031537/AmbroZX81STYLE.zip)
.
![AmbroZX81STYLE](https://user-images.githubusercontent.com/34916641/153173893-ecefdcea-e4cf-49ea-95c9-683bf12ba802.png)

**Comment by PakkunKinoppi** [comment]
superb !

**Comment by raydac** [comment]
I have added the skin into snapshot

**Comment by Alessandro1970** [comment]
:v:  Thank you

**Comment by raydac** [comment]
you can try [snapshot](https://github.com/raydac/zxpoly/releases/tag/2.3.1-S)

**Comment by Alessandro1970** [comment]
Thank you
