### ISSUE TITLE
Poke Finder/Poke Memory

### ISSUE THREAD

**Issue by Alvarez81** [raydac/zxpoly#69]
Hi, can you port/add **_poke finder_** menu from Fuse to ZxPoly, please ?

![Untitled 2](https://user-images.githubusercontent.com/39189763/166199979-209cb74b-c434-4cff-87f4-b41e6e65955e.png)

**Comment by Haroldo64** [comment]
Probably here you can find all what you may need.
https://www.the-tipshop.co.uk/
Follow hints how to work.

Maybe the support for Romantic Robot **MultifaceONE cartridge** would be better, but I do not know if ZxPoly could run the MultifaceONE, I do not succeed in loading the rom in the ZxPoly neither by Load menu nor drag'&'drop rom-file into Emulator directly.

Here there are the **MultifaceONE** source, manual and roms:
https://speccy4ever.speccy.org/_RR.htm

**Comment by Alvarez81** [comment]
Ok, thanks. Got up info from https://www.the-tipshop.co.uk/
