### ISSUE TITLE
Drag and drop skill 

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#7]
Hi, could you enanched the ZxPoly with the ability for Drag'n'Drop SNA, Z80 and TAP files ?

**Comment by raydac** [comment]
@Alessandro1970 you can try snapshot

**Comment by Alessandro1970** [comment]
I have run a lot of z80 and SNA games, it works well.

But I didn't succeed in loading any TAP or TZX with drag'n'drop

**Comment by Alessandro1970** [comment]
Ok, so we can close.
The drag'n'drop is still workng well
