### ISSUE TITLE
Turbo button stucks

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#70]
Hi.
Sometimes frequently the TURBO button is out of sync with the menu.
Pressing the "turbo button" in the menu makes the tick not work in the menu (if it is on, in the menu remains off). This at least in the Windows version.

_The problem occurs when you press the button first, but if you use the menu everything works, i.e. pressing the button does not update the menu_

![Untitled 2](https://user-images.githubusercontent.com/34916641/166657249-bff6a891-cbbf-40cb-80c1-4fe729f8bda1.png)

**Comment by Haroldo64** [comment]
Same problem on my PC

**Comment by raydac** [comment]
you can try [2.3.1-SNAPSHOT](https://github.com/raydac/zxpoly/releases/tag/2.3.1-S)

**Comment by Alessandro1970** [comment]
Thank you
