### ISSUE TITLE
Ula Plus 

### ISSUE THREAD

**Issue by Alvarez81** [raydac/zxpoly#72]
Hi everyone,
this emulator is getting better every day and because of Java it works almost everywhere.
If you could implement or be able to insert support for the ULA Plus it would be the TOP.

http://abrimaal.pro-e.pl/zx/ulaplus.htm
https://sites.google.com/site/ulaplus/

Cybernoid for ZX Spectrum with Ula Plus:
![cybernoid1-4](https://user-images.githubusercontent.com/39189763/170187139-3db60845-c439-4a1e-a330-05160a71f74b.png)

DanDare III for ZX Spectrum with Ula Plus:
![dandare3-3](https://user-images.githubusercontent.com/39189763/170187422-15e1dbb1-7df9-4cab-acdd-f05831d0c156.png)

**Comment by Haroldo64** [comment]
Hi, thank you for this kind of enhancement; this is much appreciated and very useful

**Comment by PakkunKinoppi** [comment]
Hi, this will be a beautiful and wonderful upgrade !

**Comment by Alvarez81** [comment]
ULAplus final official version of the specification is version 1.1
https://sinclair.wiki.zxnet.co.uk/wiki/ULAplus

**Comment by rossimariolee** [comment]
**Hi, this is wonderful upgrade really !!!**

**Comment by Alvarez81** [comment]
@rossimariolee  Yes, it is !

**Comment by Alessandro1970** [comment]
This is a very welcome improvement for me too

**Comment by Alvarez81** [comment]
Good morning, any news ?

**Comment by raydac** [comment]
I have added support of ULA Plus palette (it should be turned on in preferences) into SNAPSHOT

**Comment by Haroldo64** [comment]
magnificent !!!

**Comment by Alessandro1970** [comment]
Really a great job, great !!!

**Comment by Alvarez81** [comment]
Perfect, beautiful job !

Thank YOU !

**Comment by raydac** [comment]
keep in mind that ULA Palette info is supported by standard only for SZX snapshots

**Comment by Alessandro1970** [comment]
Ok, thanks
