### ISSUE TITLE
Virtual keyboard skin Spectrum+2 Style

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#75]
@raydac 

Hello everybody,
Since ZxPoly can use Amstradt ROMs Spectrum+2, I decided to ask you to add this Virtual Keyboard skin with a suitable style and compatible with the keys positions of this beautiful and very versatile emulator.

(SVG - rev 3)
[Ambroplustwo.zip](https://github.com/raydac/zxpoly/files/8885372/Ambroplustwo.zip)

![bitmap](https://user-images.githubusercontent.com/34916641/173221811-afee5460-8aef-46fb-b572-b9f605fe1362.png)

**Comment by Alvarez81** [comment]
It is very beautiful, it seems real

**Comment by Haroldo64** [comment]
I seem to see something similarly beautiful to my old Spectrum + 3 black.
It is very good!

**Comment by PakkunKinoppi** [comment]
I really like this skin

**Comment by Alessandro1970** [comment]
Thank you.
I like a lot this emulator !!!

**Comment by raydac** [comment]
I have added it into snapshot

**Comment by Alessandro1970** [comment]
Thank you
