### ISSUE TITLE
Pre-built 2.3.1-SNAPSHOT does not work

### ISSUE THREAD

**Issue by Alvarez81** [raydac/zxpoly#76]
Hi, I have downloaded this morning the Pre-built 2.3.1-SNAPSHOT (windows version) but it does not succeed in loading TZX files and it does not start from executable anymore.
To run ZxPoly now I have to run only "start_log.cmd" file and it goes slowly and wrong:

![Untitled 2](https://user-images.githubusercontent.com/39189763/173994704-1bf41c6f-ddd3-4b45-812d-1283f176a448.png)

**Comment by raydac** [comment]
looks like that something happened during add CLI, I have improved exe launcher, try please

**Comment by Alvarez81** [comment]
Now the emulator starts but cannot load TZX files, too slow or sometihing goes wrong anth game hangs.
Try to load this:
[Xarax (1987)(Firebird).zip](https://github.com/raydac/zxpoly/files/8917111/Xarax.1987.Firebird.zip)

**Comment by Alvarez81** [comment]
Problem involves only TZX files not tap.

**Comment by Alvarez81** [comment]
Problem solved !
Thank you
