### ISSUE TITLE
Keyboard Png

### ISSUE THREAD

**Issue by Haroldo64** [raydac/zxpoly#8]
Hi,
Can you use this or something similar for virtual keyboard ?

![48k_kbd](https://user-images.githubusercontent.com/53178600/108169221-b83ae580-70f8-11eb-8570-f954ccf34122.png)

![spectrum-48-keyboard](https://user-images.githubusercontent.com/53178600/108169299-cf79d300-70f8-11eb-80a9-6fb04f1dd146.png)

![spectrum-128-keyboard](https://user-images.githubusercontent.com/53178600/108169310-d274c380-70f8-11eb-9861-58749cf6d8fb.png)

Bye

**Comment by Alessandro1970** [comment]
Oh yes !
...but in this case I prefear this one, more readable and very fine:

![ZX_128_KB](https://user-images.githubusercontent.com/34916641/108211261-c86cb800-712c-11eb-9630-2b3d576c4447.png)

**Comment by Alvarez81** [comment]
Great this one @Alessandro1970

**Comment by raydac** [comment]
I can make only zx48 version for keyboard because support of macro-keys from zx 128 needs too much rework

**Comment by raydac** [comment]
I have added one more Zx48 based variant, it can be selected through preferences, you can try snapshot

**Comment by Alvarez81** [comment]
The 48k variati is quite good, maybe a plus version ?

**Comment by Alessandro1970** [comment]
The 48k variant is very fine, thanks !!!
A plus variat could be fine too
