### ISSUE TITLE
Reduce preferences screen, is too big

### ISSUE THREAD

**Issue by Haroldo64** [raydac/zxpoly#81]
The preferences scheme has gotten a little too big.
It would probably be necessary to create new options in the menu such as **Setup Joystick** in order to streamline the preferences window by removing this section and putting it in a dedicated screen.

Something like this, with the correct icons (not mine):
![Untitled 3](https://user-images.githubusercontent.com/53178600/176600166-3b3f9cf4-def1-4765-b1c0-254b4d85d94d.png)

**Comment by raydac** [comment]
You are right, I will split preferences into tabs

**Comment by Haroldo64** [comment]
Thank you

**Comment by raydac** [comment]
I have made changes and you can take a look at SNAPSHOT

**Comment by Haroldo64** [comment]
Very good, thanks
