### ISSUE TITLE
Error while loading Eklhaft 2 demo

### ISSUE THREAD

**Issue by rossimariolee** [raydac/zxpoly#84]
Hi @raydac 
This demo loads in other emulators like fuse, it at the end of loading on ZxPoly it resets (must be loaded in 48k mode).

[Eklhaft2.zip](https://github.com/raydac/zxpoly/files/9138256/Eklhaft2.zip)

**Comment by Alvarez81** [comment]
If you run it on zxmak2 emulator you can see that ZxPoly has got some border/timings problems yet

ZXMAK2:
![eee](https://user-images.githubusercontent.com/39189763/179707349-9c67ca84-0ea4-4b22-b8bb-1e21b302fe22.jpg)

**Comment by Alessandro1970** [comment]
This demo must be run in 48k mode with compatible 48k ROM.
I you use this rom in ZxPoly it works good, th only problem is the border issue.
[ZX48_v2EN.zip](https://github.com/raydac/zxpoly/files/9573524/ZX48_v2EN.zip)
Drag'n'drop this rom and then load the tap demo !!!

**Comment by Alessandro1970** [comment]
...!
![Untitled 2](https://user-images.githubusercontent.com/34916641/190360140-2c644e62-293e-4c89-be3c-852694963acc.png)

**Comment by rossimariolee** [comment]
ZX48_v2EN: this worked very well ! Thank you
