### ISSUE TITLE
Options are no longer saved on exit

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#86]
Options are no longer saved on exit, if I change the indicator panel, the joystick and the other commands (in this menu) when I restart the last choice is not saved.
Could you put the option to permanently save changes at the bottom of the **option menu** ?
![d](https://user-images.githubusercontent.com/34916641/187128803-b8119b81-51b7-4b99-9db5-2f4753a3ef7b.png)

**Comment by raydac** [comment]
try SNAPSHOT

**Comment by Alessandro1970** [comment]
Ok, thank you.
