### ISSUE TITLE
Z80 test failure

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#87]
Hi, Z80 test revision 1.2 reports 2 failures and some skipped tests:
![Untitled 5](https://user-images.githubusercontent.com/34916641/190961525-f6bf0341-2a20-4232-ac47-22ce152c42ea.png)

Test 1.2 revision:
[z80full.zip](https://github.com/raydac/zxpoly/files/9596564/z80full.zip)

**Comment by raydac** [comment]
interesting that FUSE has failed for all 4  'NOP tests, I have internal fix for 'NOP (activated by flag) but in the case FUSE tests (which I use) they stop work and I still think is it would be good to use my fix or not

**Comment by Alessandro1970** [comment]
Great, all tests passed !
![Untitled 2](https://user-images.githubusercontent.com/34916641/194473102-c8a1e9c1-dd22-4cac-a2ce-fa283e630051.png)
