### ISSUE TITLE
Kempston Mouse pointer doesn't move

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#88]
Hi,
I cannot succeed in moving or using the mouse pointer with this Kempston mouse interface driver for Spectrum BASIC.
[Preferences: kempston mouse allowed **ON** - Trap Mouse **ON**]
Can someone tell me how I may move the pointer ?
[README.zip](https://github.com/raydac/zxpoly/files/9935636/README.zip)

[mouse.zip](https://github.com/raydac/zxpoly/files/9935637/mouse.zip)
More info here: https://spectrumcomputing.co.uk/entry/14620/ZX-Spectrum/Kempston_Mouse_Interface_Driver
or here: https://k1.spdns.de/Vintage/Sinclair/82/Peripherals/Mouse%20Interfaces/Kempston%20Mouse%20Interface/Kempston%20Mouse%20Interface%20Driver/

![Untitled 2](https://user-images.githubusercontent.com/34916641/199906378-89f960e4-1214-49be-a9bf-82b25df9ae73.png)

**Comment by Alvarez81** [comment]
@raydac 
It does not work to me too, it should show an arrow not a mouse with "ESC" word.

**Comment by PakkunKinoppi** [comment]
It doesn't even work for me, I tried it with Speccy emulator and it immediately shows the mouse arrow, but this doesn't grab the mouse.

**Comment by raydac** [comment]
I use ports for kempston mouse 
0xFBDF - X
0xFFDF - Y
0xFADF - button

in provided program, in basic listing I don't see any port reading, it reads some ram cells in 60000, 60827, 60828, may be something should read mouse coords and write there? may bne some special basic version?

**Comment by Alessandro1970** [comment]
This mouse.z80 program does not work well with emulators BTW the mouse.drv loads fine and can be used if needed.

The **ZxPoly works well** in mouse Kempstone emulation, the right app to be used to is this:
[KempstonToolkit.zip](https://github.com/raydac/zxpoly/files/10989631/KempstonToolkit.zip)


![Mouse](https://user-images.githubusercontent.com/34916641/225592386-d6910633-d8dd-414f-a02f-7002e0f4d922.png)
