### ISSUE TITLE
Rom files

### ISSUE THREAD

**Issue by Haroldo64** [raydac/zxpoly#9]
Is there any way to use ours firmware/roms ?
I would like to load roms from my HD, where are they stored ?

**Comment by raydac** [comment]
now rom downloaded, converted into single block and saved in folder .zxpolyemul/cache (it depends on OS where the folder situated, under Linux it is in root of home folder), I can provide way in preferences to define path to single block ROM file for ZXSpectrum 128+TRDOS represented as solid 48k file

**Comment by raydac** [comment]
I have added option into preferences to define custom ROM file path so that you can try snapshot, it recognizing ROM as single mono-file so that if you have Basic48+Basic128+TRDOS then you should merge them into single file

**Comment by Haroldo64** [comment]
Thank you.
What kind of program do you use, on windows, to merge these files ?

**Comment by raydac** [comment]
I don't use Windows but as I know binary files can be merged through command line `COPY /B File1.bin + File2.bin file3.bin`

**Comment by Alessandro1970** [comment]
It worked fine for me!
On windows the ".zxpolyemul" is located here:
C:\Users\"USER"\AppData\Roaming\.zxpolyemul\cache\

As soon as possible I'll try on my MAC

Thank you

**Comment by Haroldo64** [comment]
It worked for me too, thanks
