### ISSUE TITLE
A way to deselect/unload custom rom file

### ISSUE THREAD

**Issue by Alessandro1970** [raydac/zxpoly#91]
Hi, I do not succeed in removing/unloading or deselecting the custom rom from the dialog window once loaded and restarted the ZxPoly.
Or an **eject button** needed.

![Untitled 4](https://user-images.githubusercontent.com/34916641/225595098-d9b4426a-ea8d-40ee-acc1-4198718e9bf0.png)

**Comment by raydac** [comment]
not very clear for me, do you want to stop use custom rom? just make field empty in the case

**Comment by Alessandro1970** [comment]
Ok, the way to remove the file (custom-rom once loaded) is delete manually all the line then press enter.
I mean to implement a button to eject the rom and clear the line.

**Comment by raydac** [comment]
good idea, I will add button to clear the field

**Comment by raydac** [comment]
added button to clear selection

**Comment by Alessandro1970** [comment]
It works fine.
Thank you
